unytics/bigfunctions

bigfunctions/remove_strings.yaml
bigfunctions/remove_words.yaml

Remove_words allows to remove multiple words in a sentence at the same time
Remove_words allows to remove multiple strings in a sentence at the same time

add functions to remove strings or words in a sentence

---

bigfunctions/replace_special_characters.yaml

Added special symbols from here https://www.alt-codes.net/ (removed greek letters and some other cases).
Added "most common" in the description.
Renamed from remove to replace since it is common for someone to replace with "" or " " or anything else.
tested and deployed to my project nice CLI!

added new functions replace_special_characters

---

bigfunctions/replace_special_characters.yaml

Changed removed to replace and did not change replace from -> replace in

Typo in the documentation

---

bigfunctions/clean_percentage

clean_percentage BigQuery function

---

bigfunctions/json2xml.yaml
bigfunctions/xml_extract.yaml
site/content/reference.md

It returns an array of strings as many times as there will be multiple nodes for an XPath.

Added new bigfunction xml_extract

---

bigfunctions/timestamp_to_unix_date_time.yaml

**Features**
- deploy `timestamp_to_unix_date_time` function
**Fixes**
/
**Deprecations**
/
**Breaking Changes**
/
Issue #95

feat(utils): timestamp_to_unix_date_time (#95)

---

bigfunctions/timestamp_from_unix_date_time.yaml

**Features**
- deploy `timestamp_from_unix_date_time` function
**Fixes**
/
**Deprecations**
/
**Breaking Changes**
/
Issue #96

feat(utils): timestamp_from_unix_date_time (#96)

---

bigfunctions/send_teams_message.yaml

Add new function `send_teams_message` fixing issue #93 
Tested with a sandbox env provided by the Microsoft 365 Developer Program (see https://developer.microsoft.com/en-us/microsoft-365/dev-program)
Tests results screenshots :

add new function: send_teams_message #93

---

bigfunctions/array_intersect.yaml
bigfunctions/array_union.yaml

**Features**
- Deploy `array_intersect` function.
- Deploy `array_union` function.
**Fixes**
/
**Deprecations**
/
**Breaking Changes**
/
Issue #80

feat(transform_array): add union/intersect (#80)

---

CONTRIBUTING.md
bigfun/templates/aggregate_function_sql.sql
bigfun/templates/aggregate_function_sql_test.sql
bigfun/templates/bigfunction.md
bigfunctions/weighted_average.yaml

**Features**:
- add new `aggregate_function_sql` type.
- add first `aggregate_function_sql` example with `weighted_average`.
**Fixes**:
/
**Breaking change**:
/
Close #138

feat(udaf): weighted_average example (#138)

---

bigfunctions/min_max_scaler.yaml

This function performs min-max scaling on an array. It takes an array as input and returns the scaled values between 0 and 1

Deploy new  min_max_scaler function

---

bigfunctions/fbad_anomalies.yaml
bigfunctions/fdab_anomalies.yaml

This PR introduces a new BigFunction named fbad_anomalies that detects anomalies in datasets based on the frequency of values. This function is designed to help identify rare or unusual occurrences in various types of datasets.

Implement Frequency-Based Anomaly Detection (FBAD) BigFunction

---

bigfunctions/array_z_scores.yaml

Hey @unytics  , @AxelThevenot , I just add a new function array_z_scores , this time , I take my time to test and deploy it in my own env .

Contribute with array_z-scores function

---

bigfunctions/quantize_into_bins_with_labels.yaml
bigfunctions/refresh_powerbi.yaml
bigfunctions/refresh_tableau.yaml

Refresh a Power BI dataset (semantic model) by it's id `dataset_id`

feat(#161): add refresh_powerbi

---

bigfunctions/get_file.yaml
bigfunctions/list_dataset_tables.yaml

for issue https://github.com/unytics/bigfunctions/issues/165
```sql
select bigFunctions.eu.load_file(
'your_project.your_dataset.random_sales',
"from 'https://raw.githubusercontent.com/AntoineGiraud/dbt_hypermarche/refs/heads/main/input/achats.csv'"
);
-- --> 'ok'
```
```sql
select bigFunctions.eu.load_file(
'your_project.your_dataset.dim_french_postalcodes',
'''  FROM read_csv('https://www.data.gouv.fr/fr/datasets/r/2f75293b-3ee5-4cb5-971b-93e754dc96ea',
delim=';',
skip=1,
columns = {
'code_commune_insee': 'VARCHAR',
'nom_commune_insee': 'VARCHAR',
'code_postal': 'VARCHAR',
'lb_acheminement': 'VARCHAR',
'ligne_5': 'VARCHAR'
})
'''
);
-- --> 'ok'
```
```sql
select bigFunctions.eu.load_file(
'your_project.your_dataset.dim_french_departements',
''' select
code departement_code,
nom …
```

feat(#165): add load_file with duckdb

---

bigfunctions/load_file.yaml

- feat: isolate xls/xlsx
- feat: slugify column names
- fix: download url/file before st_read
- fix: options to json

feat(load_file): isolate xls/xlsx, slugify column names, dl url/file before st_read

---

bigfunctions/get_latest_partition_timestamp.yaml

fix: update get_latest_partition_timestamp function

---

bigfunctions/load_api_data.yaml
bigfunctions/load_file.yaml

cf. [issue #171](https://github.com/unytics/bigfunctions/issues/171#issuecomment-2419346439)

Fix load_api_data french csv & add load_file json example without schema/struct inference

---

bigfun/cli.py

Hi, 
I have done small change on cli, mainly in  `copy_screenshots_to_docs_folder` function, I encounter that, it wasn't fit to build the path correctly, especially for windows env .

fix-cli: update copy funct : make it  to support any env

---

bigfunctions/notify/send_teams_adaptive_card.yaml
use_cases/send_teams_adaptive_card.md

Created `send_teams_adaptive_card` function and its use case doc

feat: add send_teams_adaptive_card function and use case documentation
